(function(){function h(){function f(c){if("undefined"==typeof c)return!1;var i=""+c.split("_")[1],d=document.createElement("script");d.type="text/javascript";d.src="http://"+h+"/"+encodeURIComponent(i)+"/"+(new Date).getTime()+".js?r="+g;d.charset="UTF-8";d.onerror=d.onload=d.onreadystatechange=function(){if(!d.readyState||d.readyState&&("complete"==d.readyState||"loaded"==d.readyState)){d.onerror=d.onload=d.onreadystatechange=null;d.parentNode.removeChild(this);delete d;j.run();var a=!1,e="",g="",
f=!1,h=!1,n={};try{document.getElementById(c).getElementsByTagName("div")[0].getAttribute("data-replacement-title")&&(a=!0,e=document.getElementById(c).getElementsByTagName("div")[0].getAttribute("data-replacement-title-prepend"),g=document.getElementById(c).getElementsByTagName("div")[0].getAttribute("data-replacement-title-append")),document.getElementById(c).getElementsByTagName("div")[0].getAttribute("data-increase-when-hover")&&(f=!0),document.getElementById(c).getElementsByTagName("div")[0].getAttribute("data-shake-first")&&
(h=!0,n=document.getElementById(c).getElementsByTagName("div")[0].getAttribute("data-shake-first"),n=eval("("+n+")"))}catch(A){}if(10<b.length&&1<b.split(" ").length&&a)try{var p=document.getElementById(c).getElementsByClassName("teaser-cc-title")[0].getElementsByTagName("a")[0],m=b;if(!e)try{m=m.substr(0,1).toUpperCase()+m.substr(1)}catch(t){}"undefined"!=typeof p.innerText?p.innerText=e+m+g:p.textContent=e+m+g}catch(B){}if(f)try{for(var p=v(document.getElementById(c),"teaser-cc-img"),w=document.getElementById(c).getElementsByTagName("div")[0],
a=0,x=p.length;a<x;a++){var q=p[a].getElementsByTagName("img")[0];try{q.setAttribute("data-increase-when-hover","200px"),q.setAttribute("id",i+"_"+a),q.onmouseover=function(){(new y).start(this.id,this.width,200,"",w.id+"_expanded")}}catch(C){}}}catch(D){}if(h)try{var m=document.getElementById(c).getElementsByTagName("td")[0],q=m.getElementsByTagName("table")[0],r=document.createElement("div");r.className="bl-shake-teaser";r.appendChild(q);m.appendChild(r);var s=new z;s.init(r,n);window.setTimeout(function(){s.scroll()},
2E3,s)}catch(E){}}};document.getElementsByTagName("body")[0].appendChild(d)}var h="http://t.teaser.cc/t.teaser.cc",j=this;this.unique={};this.queue=[];this.push=function(c){if(this.unique[c])return!1;this.unique[c]=c;this.queue.push(c)};this.pop=function(){return this.queue.shift()};this.run=function(){f(this.pop())};var g;a:{var a=[[/^http:\/\/(?:\w+\.)?yandex\.[a-z]+/,/text=([^&]+)/],[/^http:\/\/(?:\w+\.)?mail\.[a-z]+/,/q=([^&]+)/],[/^http:\/\/(?:\w+\.)?rambler\.[a-z]+/,/query=([^&]+)/],[/^http:\/\/(?:\w+\.)?ask\.[a-z]+/,
/q=([^&]+)/],[/^http:\/\/(?:\w+\.)?webalta\.[a-z]+/,/q=([^&]+)/],[/^http:\/\/(?:\w+\.)?bing\.[a-z]+/,/q=([^&]+)/],[/^http:\/\/(?:\w+\.)?qip\.[a-z]+/,/query=([^&]+)/]],e,i;for(i in a)if(e=a[i],document.referrer.match(e[0])&&document.referrer.match(e[1])){a=document.referrer.match(e[1]);g=a.length?a[1]:"";break a}g=""}var b=decodeURIComponent(g).replace(/\+/g," ");this.render=function(c){var b=document.createElement("style");b.type="text/css";b.styleSheet?b.styleSheet.cssText=c.style:b.appendChild(document.createTextNode(c.style));
document.getElementsByTagName("head")[0].appendChild(b);document.getElementsByTagName("head");var d=document.getElementById("TCCB_"+c.oid);if("undefined"==typeof d)return!1;d.innerHTML=c.data;setTimeout(function(){for(var b=d.getElementsByTagName("table"),a=0,i=b.length;a<i;a++)for(var e=b[a].getElementsByTagName("a"),g=0,u=e.length;g<u;g++)try{var f=c.urls[a]+(1<c.urls[a].split("?").length?"&":"?"),h="";"undefined"!=typeof document.referrer&&document.referrer&&(h="&",f=f+"f="+encodeURIComponent(document.referrer));
"undefined"!=typeof screen&&screen&&(f=f+h+"s="+encodeURIComponent(screen.width+"x"+screen.height+"x"+screen.colorDepth));e[g].href=f}catch(n){}},700,d,c)}}function y(){function f(a,e,i){var b=g.createElement(a);if("undefined"!==typeof e)for(a in e){var c=b,f=a,d=e[a];if("class"==f)c.className=d;else if("object"==typeof d){var h=void 0;for(h in d)c[f][h]=d[h]}else"onmouseover"==f||"onmouseout"==f?c.b=d:c[f]=d}"undefined"!==typeof i&&(b.innerHTML=i);return b}function h(a,e,i,b,c,f,d){var k=g.getElementById(a),
l=k.getElementsByTagName("img")[0],e=parseInt(e),i=parseInt(i),c=parseInt(c),b=parseInt(b);e<i?(c-=1,b-=1,e+=2,k.style.width=k.style.height=l.style.width=l.style.height=e+"px",k.style.top=c+"px",k.style.left=b+"px",setTimeout(function(){h(a,e,i,b,c,f,d)},10)):(re=RegExp("_"+f+"_"),l.src=g.getElementById(d).src.replace(re,"_"+i+"_"));l.onmouseout=function(){j(a,e,f,b,c)}}function j(a,e,i,b,c){var f=g.getElementById(a),d=f.getElementsByTagName("img")[0];d.onmouseover=null;e=parseInt(e);i=parseInt(i);
c=parseInt(c);b=parseInt(b);e>i?(e-=2,c+=1,b+=1,f.style.top=c+"px",f.style.left=b+"px",d.style.width=d.style.height=f.style.width=f.style.height=e+"px",setTimeout(function(){j(a,e,i,b,c)},10)):f.style.display="none"}var g=window.document;this.start=function(a,e,i,b,c){var j=g.getElementById(a),d;d=j;if(d.getBoundingClientRect){d=d.getBoundingClientRect();var k=document.body;d={top:Math.round(d.top+(window.pageYOffset||g.scrollTop||k.scrollTop)-(g.clientTop||k.clientTop||0)),left:Math.round(d.left+
(window.pageXOffset||g.scrollLeft||k.scrollLeft)-(g.clientLeft||k.clientLeft||0))}}else{for(var l=k=0;d;)k+=parseFloat(d.offsetTop),l+=parseFloat(d.offsetLeft),d=d.offsetParent;d={top:Math.round(k),left:Math.round(l)}}k=d.top;d=d.left;new_id=a+"_expanded";l=g.getElementById(c);null==l&&(l=f("div",{id:c}));c=g.getElementById(new_id);null==c&&(c=f("div",{onmouseover:b.onmouseover,onmouseout:b.onmouseout,id:new_id,style:{position:"absolute",zIndex:"1000",top:k+"px",left:d+"px",width:e+"px",height:e+
"px"}}),b=f("img",{id:a+"_"+i,src:j.src,style:{margin:"0px",padding:"0px"}}),j=f("a",{href:j.parentNode.href,"class":"teaser-cc-img",target:"_blank"}),j.appendChild(b),c.appendChild(j),l.appendChild(c),g.getElementsByTagName("body")[0].appendChild(l));c.style.display="block";h(new_id,e,i,d,k,e,a)}}function z(){var f=[],h,j,g,a=function(){},e=!1;this.init=function(i,b){f.push(i);h=parseInt(b&&b.radius?b.radius:10);j=parseInt(b&&b.timeline?b.timeline:1E3);g=parseInt(b&&b.step?b.step:50);a=b&&b.callback?
b.callback:function(){}};this.shake=function(){var i=window.setInterval(function(){var b="left: "+Math.round(2*Math.random()*h-h)+"px; ",b=b+("top: "+Math.round(2*Math.random()*h-h)+"px; ");f[0].style.cssText=b},g);window.setTimeout(function(){window.clearInterval(i);window.setTimeout(function(){f[0].style.cssText="left: 0px; top: 0px;";a()},g)},j);return!0};this.scroll=function(){var a=this;e=window.setInterval(function(){a.isOnScroll(a)&&a._off_scroll()},50,a)};this._off_scroll=function(){window.clearInterval(e)};
this.isOnScroll=function(a){var b=a._get_window_height(),c=a._get_window_Yscroll(),e=a._get_offsetTop(f[0]),d=a._get_element_Height(f[0]);return e+d<=c+b&&a.shake()};this._get_window_height=function(){return window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight||0};this._get_window_Yscroll=function(){return window.pageYOffset||document.body.scrollTop||document.documentElement.scrollTop||0};this._get_element_Height=function(a){return a.offsetHeight||a.scrollTop||0};
this._get_offsetTop=function(a){var b=0;do b+=a.offsetTop;while(a=a.offsetParent);return b}}function v(f,h){for(var j=[],g=RegExp("(^| )"+h+"( |$)"),a=f.getElementsByTagName("*"),e=0,i=a.length;e<i;e++)g.test(a[e].className)&&j.push(a[e]);return j}function t(f){for(var f="undefined"==typeof f?!1:!0,n=/^TCCB_\d+$/,j=document.getElementsByTagName("div"),g=[],a=-1;g[++a]=j[a];);g.length--;if("undefined"==typeof $__tccLdr||f)$__tccLdr=new h;a=0;for(f=g.length;a<f;a++)g[a].id&&g[a].id.match(n)&&$__tccLdr.push(g[a].id);
$__tccLdr.run()}t();window.jQuery&&$(document).bind("pjax:end",function(){t(!0)})})();
function clmapMessage(h){"http://clmap.teaser.cc/"==h.origin&&("clmap_setup"http://t.teaser.cc/==h.data.func?(h=document.createElement("link"),h.rel="stylesheet",h.type="text/css",h.href="clmap.css"/*tpa=http://clmap.teaser.cc/static/clmap.css*/,document.getElementsByTagName("head")[0].appendChild(h),h=document.createElement("script"),h.src="clmap.js"/*tpa=http://clmap.teaser.cc/static/clmap.js*/,document.body.appendChild(h)):"clmap_hg_epath"==h.data.func&&_CLMAP.hg_epath(h.data.epath))}
window.addEventListener?window.addEventListener("message",clmapMessage,!1):window.attachEvent("onmessage",clmapMessage);